<?xml version="1.0" encoding="utf-8"?><Database Name="sms" Class="schoolDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-6TO1UR3\SQLEXPRESS;Initial Catalog=sms;Integrated Security=True" SettingsObjectName="SchoolManagementSystem.Properties.Settings" SettingsPropertyName="smsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="roleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roleName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.student" Member="students">
    <Type Name="student">
      <Column Name="sid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nic" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.EventTb" Member="EventTbs">
    <Type Name="EventTb">
      <Column Name="eventID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="eventName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="venue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.roles_delete" Method="roles_delete">
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.roles_getRoles" Method="roles_getRoles">
    <ElementType Name="roles_getRolesResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.roles_insert" Method="roles_insert">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="status" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.roles_search" Method="roles_search">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="roles_searchResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.roles_update" Method="roles_update">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="status" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_delete" Method="student_delete">
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_getStudent" Method="student_getStudent">
    <ElementType Name="student_getStudentResult">
      <Column Name="sid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="nic" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="birthdate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.student_insert" Method="student_insert">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="gender" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="image" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_insert_withoutImage" Method="student_insert_withoutImage">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="gender" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_update" Method="student_update">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="gender" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="image" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getRoleId" Method="getRoleId" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getStudentId" Method="getStudentId" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_search" Method="student_search">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="student_searchResult">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NIC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FNAME" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LNAME" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BIRTHDATE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TELEPHONE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.student_update_withoutImage" Method="student_update_withoutImage">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="gender" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getEventId" Method="getEventId" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.event_insert" Method="event_insert">
    <Parameter Name="eName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="eDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="eVenue" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="time" Type="System.TimeSpan" DbType="Time" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.event_update" Method="event_update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="eName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="eDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="eVenue" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="time" Type="System.TimeSpan" DbType="Time" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.event_view" Method="event_view">
    <Parameter Name="eName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="event_viewResult">
      <Column Name="eventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="eventName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="venue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.event_delete" Method="event_delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>