<?xml version="1.0" encoding="utf-8"?><Database Name="sms" Class="schoolDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-TM7VHQ4;Initial Catalog=sms;Integrated Security=True" SettingsObjectName="SchoolManagementSystem.Properties.Settings" SettingsPropertyName="smsDB" Provider="System.Data.SqlClient" />
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="roleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roleName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.student" Member="students">
    <Type Name="student">
      <Column Name="sid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nic" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="eventID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="eventName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="venue" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="time" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.roles_delete" Method="roles_delete">
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.roles_getRoles" Method="roles_getRoles">
    <ElementType Name="roles_getRolesResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.roles_insert" Method="roles_insert">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="status" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.roles_search" Method="roles_search">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="roles_searchResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.roles_update" Method="roles_update">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="status" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_delete" Method="student_delete">
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_getStudent" Method="student_getStudent">
    <ElementType Name="student_getStudentResult">
      <Column Name="sid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="nic" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="birthdate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="class" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.student_insert" Method="student_insert">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="gender" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <Parameter Name="class" Type="System.Int32" DbType="Int" />
    <Parameter Name="image" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_insert_withoutImage" Method="student_insert_withoutImage">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="gender" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <Parameter Name="class" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_search" Method="student_search">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="student_searchResult">
      <Column Name="sid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="nic" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="birthdate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="class" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.student_update" Method="student_update">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="gender" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="image" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <Parameter Name="class" Type="System.Int32" DbType="Int" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.student_update_withoutImage" Method="student_update_withoutImage">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="firstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="telephone" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="birthDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="gender" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="grade" Type="System.Int32" DbType="Int" />
    <Parameter Name="class" Type="System.Int32" DbType="Int" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.systemLogin" Method="systemLogin">
    <Parameter Name="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="systemLoginResult">
      <Column Name="userName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="roleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getRoleId" Method="getRoleId" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getStudentId" Method="getStudentId" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.class_getClasses" Method="class_getClasses">
    <ElementType Name="class_getClassesResult">
      <Column Name="classId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="className" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.grades_getGrades" Method="grades_getGrades">
    <ElementType Name="grades_getGradesResult">
      <Column Name="gradeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gradeName" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.student_advanceSearch" Method="student_advanceSearch">
    <Parameter Name="nic" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Parameter Name="fName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="gradeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="classId" Type="System.Int32" DbType="Int" />
    <ElementType Name="student_advanceSearchResult">
      <Column Name="sid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="nic" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="birthdate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="class" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.privileges_HomePrivileges" Method="privileges_HomePrivileges">
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="privileges_HomePrivilegesResult">
      <Column Name="roleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="student" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="staff" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="classes" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="courses" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="timetables" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="payments" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="events" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="library" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="examinations" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="inventory" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="roles" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="users" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.privileges_getPrivileges" Method="privileges_getPrivileges">
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="privileges_getPrivilegesResult">
      <Column Name="roleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studAdd" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="studEdit" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="studDelete" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.users_search" Method="users_search">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="users_searchResult">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="roleId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.users_viewUsers" Method="users_viewUsers">
    <ElementType Name="users_viewUsersResult">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="roleId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.users_deleteUser" Method="users_deleteUser">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getUserId" Method="getUserId" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.users_insert" Method="users_insert">
    <Parameter Name="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.users_changePassword" Method="users_changePassword">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="currentPassword" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="newPassword" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="users_changePasswordResult">
      <Column Name="changedId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.event_delete" Method="event_delete">
    <Parameter Name="eid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.event_getEvent" Method="event_getEvent">
    <ElementType Name="event_getEventResult">
      <Column Name="eventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="eventName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="venue" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="time" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.event_insert" Method="event_insert">
    <Parameter Name="eventName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="venue" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="time" Type="System.TimeSpan" DbType="Time" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.event_search" Method="event_search">
    <Parameter Name="eventName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="event_searchResult">
      <Column Name="eventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="eventName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.event_update" Method="event_update">
    <Parameter Name="eventName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="venue" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="time" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="eid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getEventId" Method="getEventId" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
</Database>