USE [master]
GO

/****** Object:  Database [sms]    Script Date: 8/25/2019 2:33:28 PM ******/
CREATE DATABASE [sms]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sms', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\sms.mdf' , SIZE = 27840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'sms_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\sms_log.ldf' , SIZE = 11456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [sms] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sms] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sms] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sms] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sms] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sms] SET ARITHABORT OFF 
GO

ALTER DATABASE [sms] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sms] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sms] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sms] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sms] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sms] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sms] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sms] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sms] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sms] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sms] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sms] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sms] SET RECOVERY FULL 
GO

ALTER DATABASE [sms] SET  MULTI_USER 
GO

ALTER DATABASE [sms] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sms] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sms] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sms] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [sms] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sms] SET  READ_WRITE 
GO

